name: Python Code Quality Checks

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install MPI
        run: sudo apt-get update && sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black mypy isort bandit mpi4py

      - name: Run Black
        run: black --check .

      - name: Run Mypy
        run: mypy .

      - name: Run isort
        run: isort --check-only .

      - name: Run Bandit
        run: bandit -r .
